/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.fartsysadditions;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.Random;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class ElementsFartsysadditionsMod implements IFuelHandler, IWorldGenerator {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	public final List<Supplier<Potion>> potions = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ElementsFartsysadditionsMod() {
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.primals.brutejusticemode"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.primals.brutejusticemode")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.brutejusticemode"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.brutejusticemode")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.primals.exponentialentropy"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.primals.exponentialentropy")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.infinity"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.infinity")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.locus"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.locus")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.primals.locus"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.primals.locus")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.metal"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.metal")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.outoftime"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.outoftime")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.silentregardofstars"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.silentregardofstars")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.knowledgeneversleeps"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.knowledgeneversleeps")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.alandlongdead"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.alandlongdead")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.agentofinquiry"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.agentofinquiry")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.lunarwhale"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.lunarwhale")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.closeinthedistance"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.closeinthedistance")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.footfalls"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.footfalls")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.undertheweight"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.undertheweight")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.landslide"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.landslide")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.woethatismadness"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.woethatismadness")));
		sounds.put(new ResourceLocation("fartsysadditions", "touhou.badapple"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "touhou.badapple")));
		sounds.put(new ResourceLocation("fartsysadditions", "touhou.necrofantasia"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "touhou.necrofantasia")));
		sounds.put(new ResourceLocation("fartsysadditions", "touhou.cosmicmind"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "touhou.cosmicmind")));
		sounds.put(new ResourceLocation("fartsysadditions", "touhou.nuclearfusion"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "touhou.nuclearfusion")));
		sounds.put(new ResourceLocation("fartsysadditions", "touhou.unowenwasher"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "touhou.unowenwasher")));
		sounds.put(new ResourceLocation("fartsysadditions", "demetori.orientaldarkflight"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "demetori.orientaldarkflight")));
		sounds.put(new ResourceLocation("fartsysadditions", "demetori.necrofantasia"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "demetori.necrofantasia")));
		sounds.put(new ResourceLocation("fartsysadditions", "demetori.worldsend"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "demetori.worldsend")));
		sounds.put(new ResourceLocation("fartsysadditions", "dmc5.deviltrigger"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "dmc5.deviltrigger")));
		sounds.put(new ResourceLocation("fartsysadditions", "dmc5.burythelightmission20"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "dmc5.burythelightmission20")));
		sounds.put(new ResourceLocation("fartsysadditions", "dmc5.silverbullet"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "dmc5.silverbullet")));
		sounds.put(new ResourceLocation("fartsysadditions", "nge.cruelangelsthesis"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "nge.cruelangelsthesis")));
		sounds.put(new ResourceLocation("fartsysadditions", "slipknot.psychosocial"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "slipknot.psychosocial")));
		sounds.put(new ResourceLocation("fartsysadditions", "xc.youwillknowournames"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "xc.youwillknowournames")));
		sounds.put(new ResourceLocation("fartsysadditions", "xc2.battle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "xc2.battle")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.shadowbringers"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.shadowbringers")));
		sounds.put(new ResourceLocation("fartsysadditions", "kbr.dededestroyerz"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "kbr.dededestroyerz")));
		sounds.put(new ResourceLocation("fartsysadditions", "smash.pixelsofglory"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "smash.pixelsofglory")));
		sounds.put(new ResourceLocation("fartsysadditions", "emone"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "emone")));
		sounds.put(new ResourceLocation("fartsysadditions", "woad"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "woad")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.insatiable"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.insatiable")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.silentscream"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.silentscream")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.totheedge"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.totheedge")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.penitus"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.penitus")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.battleonthebigbridge"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.battleonthebigbridge")));
		sounds.put(new ResourceLocation("fartsysadditions", "ffxiv.exponentialentropy"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysadditions", "ffxiv.exponentialentropy")));
	}

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == ElementsFartsysadditionsMod.ModElement.class)
					elements.add((ElementsFartsysadditionsMod.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ElementsFartsysadditionsMod.ModElement::initElements);
		this.addNetworkMessage(FartsysadditionsModVariables.WorldSavedDataSyncMessageHandler.class,
				FartsysadditionsModVariables.WorldSavedDataSyncMessage.class, Side.SERVER, Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = FartsysadditionsModVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = FartsysadditionsModVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				FartsysadditionsMod.PACKET_HANDLER.sendTo(new FartsysadditionsModVariables.WorldSavedDataSyncMessage(0, mapdata),
						(EntityPlayerMP) event.player);
			if (worlddata != null)
				FartsysadditionsMod.PACKET_HANDLER.sendTo(new FartsysadditionsModVariables.WorldSavedDataSyncMessage(1, worlddata),
						(EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = FartsysadditionsModVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				FartsysadditionsMod.PACKET_HANDLER.sendTo(new FartsysadditionsModVariables.WorldSavedDataSyncMessage(1, worlddata),
						(EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;
	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			FartsysadditionsMod.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}
	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			return null;
		}
	}
	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ElementsFartsysadditionsMod elements;
		protected final int sortid;
		public ModElement(ElementsFartsysadditionsMod elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
