/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package org.hydrogenhosting.fartsysmagitechproductions;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.Random;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class ElementsFartsysmagitechproductionsMod implements IFuelHandler, IWorldGenerator {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	public final List<Supplier<Potion>> potions = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ElementsFartsysmagitechproductionsMod() {
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.athenathetirelessone"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.athenathetirelessone")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.closeinthedistance"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.closeinthedistance")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.footfalls"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.footfalls")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.metal"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.metal")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.locus"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.locus")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.metalbrutejusticemode"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.metalbrutejusticemode")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.big_boned"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.big_boned")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.papaya"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.papaya")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.the_ewer_brimmeth"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.the_ewer_brimmeth")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "la_cucuracha"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "la_cucuracha")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.exponential_entropy_primals"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.exponential_entropy_primals")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "eas"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "eas")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.betweenchipsandtunes"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.betweenchipsandtunes")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipcountry"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipcountry")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipoiljiggletune"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipoiljiggletune")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.andloveyoushallfind"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.andloveyoushallfind")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipsofthetunes"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipsofthetunes")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipsun"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipsun")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipsofnature"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipsofnature")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.chiptunetrigger"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.chiptunetrigger")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.driftveilchiptune"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.driftveilchiptune")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.dynamitechiptune"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.dynamitechiptune")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.exponentialchiptune"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.exponentialchiptune")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.nevergonnachiptune"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.nevergonnachiptune")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "kissonekinoma.motoroiljigglejungle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "kissonekinoma.motoroiljigglejungle")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.sweatychips"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.sweatychips")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "kissonekinoma.sweatysocks"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "kissonekinoma.sweatysocks")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "woad"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "woad")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "emone"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "emone")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.landslide"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.landslide")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.brutechiptune"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.brutechiptune")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.twicestricken"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.twicestricken")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.interphosp1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.interphosp1")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.alongfall"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.alongfall")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.papaya_demastered"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.papaya_demastered")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.whobringsshadow"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.whobringsshadow")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.tomorrowandtomorrow"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.tomorrowandtomorrow")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "xc2.battle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "xc2.battle")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "xcde.youwillknowournames"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "xcde.youwillknowournames")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "pokemons1.burningbattlefield"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "pokemons1.burningbattlefield")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.sandsofamber"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.sandsofamber")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.fiend"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.fiend")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.neathdarkwaters"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.neathdarkwaters")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.insatiablechips"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.insatiablechips")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.oneamongsttheweary"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.oneamongsttheweary")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.badapplefc"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.badapplefc")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "kiki.clozee_koto"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "kiki.clozee_koto")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "kiki.tuturu"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "kiki.tuturu")));
	}

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == ElementsFartsysmagitechproductionsMod.ModElement.class)
					elements.add((ElementsFartsysmagitechproductionsMod.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ElementsFartsysmagitechproductionsMod.ModElement::initElements);
		this.addNetworkMessage(FartsysmagitechproductionsModVariables.WorldSavedDataSyncMessageHandler.class,
				FartsysmagitechproductionsModVariables.WorldSavedDataSyncMessage.class, Side.SERVER, Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = FartsysmagitechproductionsModVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = FartsysmagitechproductionsModVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				FartsysmagitechproductionsMod.PACKET_HANDLER.sendTo(new FartsysmagitechproductionsModVariables.WorldSavedDataSyncMessage(0, mapdata),
						(EntityPlayerMP) event.player);
			if (worlddata != null)
				FartsysmagitechproductionsMod.PACKET_HANDLER
						.sendTo(new FartsysmagitechproductionsModVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = FartsysmagitechproductionsModVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				FartsysmagitechproductionsMod.PACKET_HANDLER
						.sendTo(new FartsysmagitechproductionsModVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;
	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			FartsysmagitechproductionsMod.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}
	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			return null;
		}
	}
	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ElementsFartsysmagitechproductionsMod elements;
		protected final int sortid;
		public ModElement(ElementsFartsysmagitechproductionsMod elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
