/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package org.hydrogenhosting.fartsysmagitechproductions;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class FartsysmagitechproductionsModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();

	public FartsysmagitechproductionsModElements() {
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.athenathetirelessone"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.athenathetirelessone")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.closeinthedistance"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.closeinthedistance")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.footfalls"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.footfalls")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.metal"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.metal")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.locus"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.locus")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.metalbrutejusticemode"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.metalbrutejusticemode")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.big_boned"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.big_boned")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.papaya"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.papaya")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.the_ewer_brimmeth"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.the_ewer_brimmeth")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "la_cucuracha"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "la_cucuracha")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.exponential_entropy_primals"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.exponential_entropy_primals")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "eas"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "eas")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.betweenchipsandtunes"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.betweenchipsandtunes")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipcountry"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipcountry")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipoiljiggletune"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipoiljiggletune")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.andloveyoushallfind"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.andloveyoushallfind")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipsofthetunes"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipsofthetunes")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipsun"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipsun")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipsofnature"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.chipsofnature")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.chiptunetrigger"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.chiptunetrigger")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.driftveilchiptune"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.driftveilchiptune")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.dynamitechiptune"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.dynamitechiptune")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.exponentialchiptune"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.exponentialchiptune")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.nevergonnachiptune"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.nevergonnachiptune")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "kissonekinoma.motoroiljigglejungle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "kissonekinoma.motoroiljigglejungle")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.sweatychips"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.sweatychips")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "kissonekinoma.sweatysocks"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "kissonekinoma.sweatysocks")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "woad"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "woad")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "emone"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "emone")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.landslide"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.landslide")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.brutechiptune"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.brutechiptune")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.twicestricken"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.twicestricken")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.interphosp1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.interphosp1")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.alongfall"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.alongfall")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.papaya_demastered"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.papaya_demastered")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.whobringsshadow"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.whobringsshadow")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.tomorrowandtomorrow"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.tomorrowandtomorrow")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "xc2.battle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "xc2.battle")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "xcde.youwillknowournames"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "xcde.youwillknowournames")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "pokemons1.burningbattlefield"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "pokemons1.burningbattlefield")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.sandsofamber"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.sandsofamber")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.fiend"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.fiend")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.neathdarkwaters"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.neathdarkwaters")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.insatiablechips"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.insatiablechips")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "ffxiv.oneamongsttheweary"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "ffxiv.oneamongsttheweary")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "fartsy.badapplefc"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "fartsy.badapplefc")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "kiki.clozee_koto"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "kiki.clozee_koto")));
		sounds.put(new ResourceLocation("fartsysmagitechproductions", "kiki.tuturu"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsysmagitechproductions", "kiki.tuturu")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("fartsysmagitechproductions").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == FartsysmagitechproductionsModElements.ModElement.class)
						elements.add((FartsysmagitechproductionsModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(FartsysmagitechproductionsModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	private int messageID = 0;

	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		FartsysmagitechproductionsMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}

		protected final FartsysmagitechproductionsModElements elements;
		protected final int sortid;

		public ModElement(FartsysmagitechproductionsModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
