modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="fartsysadditions"
version="1.0.0"
displayName="FartsysAdditions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="profe, MCreator"

[[dependencies.fartsysadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



