modLoader="javafml"
loaderVersion="[40,)"
license="Custom license"

[[mods]]
modId="fartsys_additions"
version="1.0.2"
displayName="Fartsy's Additions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://forums.firehostredux.com"
logoFile="logo.png"
authors="ProfessorFartsalot"
description='''
Add niche stuff to Minecraft with this stinky mod!
'''

[[dependencies.fartsys_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




