modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="fartsysmagitechproductions"
version="2.0.0"
displayName="Fartsy's Magitech Productions"
credits="https://github.com/ProfessorFartsalot/Fartsys-Additions"
displayURL="https://wiki.hydrogenhosting.org"
logoFile="logo.png"
authors="Fartsy"
description='''
A collection of ideas for Minecraft. Music from FF14, KissoneKinoma, and Fartsy.
'''

[[dependencies.fartsysmagitechproductions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




