
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.firehostredux.fartsysadditions.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import com.firehostredux.fartsysadditions.item.WaffleOfAssDestructionItem;
import com.firehostredux.fartsysadditions.item.ShartTwoThousandItem;
import com.firehostredux.fartsysadditions.item.ShartTwoMillionItem;
import com.firehostredux.fartsysadditions.item.ShartTwoItem;
import com.firehostredux.fartsysadditions.item.ShartTwoHundredThousandItem;
import com.firehostredux.fartsysadditions.item.ShartTwoHundredItem;
import com.firehostredux.fartsysadditions.item.ShartTwentyThousandItem;
import com.firehostredux.fartsysadditions.item.ShartTwentyMillionItem;
import com.firehostredux.fartsysadditions.item.ShartTwentyItem;
import com.firehostredux.fartsysadditions.item.ShartThousandItem;
import com.firehostredux.fartsysadditions.item.ShartTenThousandItem;
import com.firehostredux.fartsysadditions.item.ShartTenMillionItem;
import com.firehostredux.fartsysadditions.item.ShartTenItem;
import com.firehostredux.fartsysadditions.item.ShartSpecialItem;
import com.firehostredux.fartsysadditions.item.ShartOneItem;
import com.firehostredux.fartsysadditions.item.ShartMillionItem;
import com.firehostredux.fartsysadditions.item.ShartHundredThousandItem;
import com.firehostredux.fartsysadditions.item.ShartHundredItem;
import com.firehostredux.fartsysadditions.item.ShardWindItem;
import com.firehostredux.fartsysadditions.item.ShardWaterItem;
import com.firehostredux.fartsysadditions.item.ShardUnaspectedItem;
import com.firehostredux.fartsysadditions.item.ShardLightningItem;
import com.firehostredux.fartsysadditions.item.ShardIceItem;
import com.firehostredux.fartsysadditions.item.ShardFireItem;
import com.firehostredux.fartsysadditions.item.ShardEarthItem;
import com.firehostredux.fartsysadditions.item.PVCPlasticItem;
import com.firehostredux.fartsysadditions.item.LaCucurachaItem;
import com.firehostredux.fartsysadditions.item.JRWhoBringsShadowItem;
import com.firehostredux.fartsysadditions.item.JRWaywardDaughterItem;
import com.firehostredux.fartsysadditions.item.JRTwiceStrickenItem;
import com.firehostredux.fartsysadditions.item.JRTriumphDissidiaNTItem;
import com.firehostredux.fartsysadditions.item.JRTornFromTheHeavensOrchestralItem;
import com.firehostredux.fartsysadditions.item.JRTomorrowAndTomorrowItem;
import com.firehostredux.fartsysadditions.item.JRToTheEdgeItem;
import com.firehostredux.fartsysadditions.item.JRTheEwerBrimmethItem;
import com.firehostredux.fartsysadditions.item.JRSteelReasonItem;
import com.firehostredux.fartsysadditions.item.JRShadowbringersItem;
import com.firehostredux.fartsysadditions.item.JRScreamItem;
import com.firehostredux.fartsysadditions.item.JRSandsOfAmberItem;
import com.firehostredux.fartsysadditions.item.JRPenitusItem;
import com.firehostredux.fartsysadditions.item.JRPapayaDemasteredItem;
import com.firehostredux.fartsysadditions.item.JRPaPayaItem;
import com.firehostredux.fartsysadditions.item.JROneAmongstTheWearyItem;
import com.firehostredux.fartsysadditions.item.JRNightbloomItem;
import com.firehostredux.fartsysadditions.item.JRNeathDarkWatersItem;
import com.firehostredux.fartsysadditions.item.JRMetalItem;
import com.firehostredux.fartsysadditions.item.JRMetalBruteJusticeModeItem;
import com.firehostredux.fartsysadditions.item.JRLunarWhaleItem;
import com.firehostredux.fartsysadditions.item.JRLunacyItem;
import com.firehostredux.fartsysadditions.item.JRLocusItem;
import com.firehostredux.fartsysadditions.item.JRLandslideItem;
import com.firehostredux.fartsysadditions.item.JRInterphosP1Item;
import com.firehostredux.fartsysadditions.item.JRInsatiableItem;
import com.firehostredux.fartsysadditions.item.JRImaginationItem;
import com.firehostredux.fartsysadditions.item.JRHicSvntLeonesItem;
import com.firehostredux.fartsysadditions.item.JRGiveItAllItem;
import com.firehostredux.fartsysadditions.item.JRFromTheHeavensItem;
import com.firehostredux.fartsysadditions.item.JRFootfallsItem;
import com.firehostredux.fartsysadditions.item.JRFiendItem;
import com.firehostredux.fartsysadditions.item.JRExponentialEntropyPrimalsItem;
import com.firehostredux.fartsysadditions.item.JREscapeItem;
import com.firehostredux.fartsysadditions.item.JRCloseInTheDistanceItem;
import com.firehostredux.fartsysadditions.item.JRBigBonedItem;
import com.firehostredux.fartsysadditions.item.JRAthenaTheTirelessOneItem;
import com.firehostredux.fartsysadditions.item.JRAndLoveYouShallFindItem;
import com.firehostredux.fartsysadditions.item.JRALongFallItem;
import com.firehostredux.fartsysadditions.item.FCWaywardDaughterItem;
import com.firehostredux.fartsysadditions.item.FCTornFromTheHeavensOrchestralItem;
import com.firehostredux.fartsysadditions.item.FCToTheEdgeItem;
import com.firehostredux.fartsysadditions.item.FCTheEwerBrimmethItem;
import com.firehostredux.fartsysadditions.item.FCSteelReasonItem;
import com.firehostredux.fartsysadditions.item.FCShadowbringersItem;
import com.firehostredux.fartsysadditions.item.FCScreamItem;
import com.firehostredux.fartsysadditions.item.FCPenitusItem;
import com.firehostredux.fartsysadditions.item.FCNightbloomItem;
import com.firehostredux.fartsysadditions.item.FCMetalItem;
import com.firehostredux.fartsysadditions.item.FCMetalBruteJusticeModeItem;
import com.firehostredux.fartsysadditions.item.FCLunarWhaleItem;
import com.firehostredux.fartsysadditions.item.FCLunacyItem;
import com.firehostredux.fartsysadditions.item.FCLocusItem;
import com.firehostredux.fartsysadditions.item.FCInsatiableItem;
import com.firehostredux.fartsysadditions.item.FCImaginationItem;
import com.firehostredux.fartsysadditions.item.FCFromTheHeavensItem;
import com.firehostredux.fartsysadditions.item.FCFootfallsItem;
import com.firehostredux.fartsysadditions.item.FCFiendItem;
import com.firehostredux.fartsysadditions.item.FCExponentialEntropyPrimalsItem;
import com.firehostredux.fartsysadditions.item.FCEscapeItem;
import com.firehostredux.fartsysadditions.item.FCCloseInTheDistanceItem;
import com.firehostredux.fartsysadditions.item.FCBigBonedItem;
import com.firehostredux.fartsysadditions.item.FCAthenaTheTirelessOneItem;
import com.firehostredux.fartsysadditions.item.FCAndLoveYouShallFindItem;
import com.firehostredux.fartsysadditions.item.EnchantedRedstoneInkItem;
import com.firehostredux.fartsysadditions.item.EnchantedQuartzInkItem;
import com.firehostredux.fartsysadditions.item.EnchantedNetherBrickInkItem;
import com.firehostredux.fartsysadditions.item.EnchantedLapisInkItem;
import com.firehostredux.fartsysadditions.item.EnchantedIronInkItem;
import com.firehostredux.fartsysadditions.item.EnchantedGoldInkItem;
import com.firehostredux.fartsysadditions.item.EnchantedGlowstoneInkItem;
import com.firehostredux.fartsysadditions.item.EnchantedEnderPearlInkItem;
import com.firehostredux.fartsysadditions.item.EnchantedEmeraldInkItem;
import com.firehostredux.fartsysadditions.item.EnchantedDiamondInkItem;
import com.firehostredux.fartsysadditions.item.DebugItemItem;
import com.firehostredux.fartsysadditions.item.CrystalWindItem;
import com.firehostredux.fartsysadditions.item.CrystalWaterItem;
import com.firehostredux.fartsysadditions.item.CrystalUnaspectedItem;
import com.firehostredux.fartsysadditions.item.CrystalLightningItem;
import com.firehostredux.fartsysadditions.item.CrystalIceItem;
import com.firehostredux.fartsysadditions.item.CrystalFireItem;
import com.firehostredux.fartsysadditions.item.CrystalEarthItem;
import com.firehostredux.fartsysadditions.item.CronusItem;
import com.firehostredux.fartsysadditions.item.ClusterWindItem;
import com.firehostredux.fartsysadditions.item.ClusterWaterItem;
import com.firehostredux.fartsysadditions.item.ClusterUnaspectedItem;
import com.firehostredux.fartsysadditions.item.ClusterLightningItem;
import com.firehostredux.fartsysadditions.item.ClusterIceItem;
import com.firehostredux.fartsysadditions.item.ClusterFireItem;
import com.firehostredux.fartsysadditions.item.ClusterEarthItem;
import com.firehostredux.fartsysadditions.item.BlankG3JRItem;
import com.firehostredux.fartsysadditions.item.BlankG2JRItem;
import com.firehostredux.fartsysadditions.item.BlankG1JRItem;
import com.firehostredux.fartsysadditions.item.BagORockSaltItem;
import com.firehostredux.fartsysadditions.item.AMDYouWillKnowOurNamesRemasteredItem;
import com.firehostredux.fartsysadditions.item.AMDWhoBringsShadowItem;
import com.firehostredux.fartsysadditions.item.AMDWaywardDaughterItem;
import com.firehostredux.fartsysadditions.item.AMDTwiceStrickenItem;
import com.firehostredux.fartsysadditions.item.AMDTwiceStrickenInstrumentalItem;
import com.firehostredux.fartsysadditions.item.AMDTriumphDissidiaNTItem;
import com.firehostredux.fartsysadditions.item.AMDTornFromTheHeavensOrchestralItem;
import com.firehostredux.fartsysadditions.item.AMDTomorrowAndTomorrowItem;
import com.firehostredux.fartsysadditions.item.AMDToTheEdgeItem;
import com.firehostredux.fartsysadditions.item.AMDTheEwerBrimmethItem;
import com.firehostredux.fartsysadditions.item.AMDSweatySocksItem;
import com.firehostredux.fartsysadditions.item.AMDSweatyChipsItem;
import com.firehostredux.fartsysadditions.item.AMDSteelReasonItem;
import com.firehostredux.fartsysadditions.item.AMDShadowbringersItem;
import com.firehostredux.fartsysadditions.item.AMDScreamItem;
import com.firehostredux.fartsysadditions.item.AMDSandsOfAmberItem;
import com.firehostredux.fartsysadditions.item.AMDPenitusItem;
import com.firehostredux.fartsysadditions.item.AMDPapayaDemasteredItem;
import com.firehostredux.fartsysadditions.item.AMDPaPayaItem;
import com.firehostredux.fartsysadditions.item.AMDOneAmongstTheWearyItem;
import com.firehostredux.fartsysadditions.item.AMDNightbloomItem;
import com.firehostredux.fartsysadditions.item.AMDNeverGonnaGiveYouUpItem;
import com.firehostredux.fartsysadditions.item.AMDNeathDarkWatersItem;
import com.firehostredux.fartsysadditions.item.AMDMotorOilJiggleJungleItem;
import com.firehostredux.fartsysadditions.item.AMDMetalItem;
import com.firehostredux.fartsysadditions.item.AMDMetalBruteJusticeModeItem;
import com.firehostredux.fartsysadditions.item.AMDMelanchiptuneItem;
import com.firehostredux.fartsysadditions.item.AMDLunarWhaleItem;
import com.firehostredux.fartsysadditions.item.AMDLunacyItem;
import com.firehostredux.fartsysadditions.item.AMDLocusItem;
import com.firehostredux.fartsysadditions.item.AMDLandslideItem;
import com.firehostredux.fartsysadditions.item.AMDInterphosP1Item;
import com.firehostredux.fartsysadditions.item.AMDInsatiableItem;
import com.firehostredux.fartsysadditions.item.AMDInsatiableChipsItem;
import com.firehostredux.fartsysadditions.item.AMDImaginationItem;
import com.firehostredux.fartsysadditions.item.AMDHicSvntLeonesItem;
import com.firehostredux.fartsysadditions.item.AMDGiveItAllItem;
import com.firehostredux.fartsysadditions.item.AMDFromTheHeavensItem;
import com.firehostredux.fartsysadditions.item.AMDFootfallsItem;
import com.firehostredux.fartsysadditions.item.AMDFiendItem;
import com.firehostredux.fartsysadditions.item.AMDExponentialEntropyPrimalsItem;
import com.firehostredux.fartsysadditions.item.AMDExponentialChiptuneItem;
import com.firehostredux.fartsysadditions.item.AMDEscapeItem;
import com.firehostredux.fartsysadditions.item.AMDDynamiteItem;
import com.firehostredux.fartsysadditions.item.AMDDriftveilCityItem;
import com.firehostredux.fartsysadditions.item.AMDDevilTriggerItem;
import com.firehostredux.fartsysadditions.item.AMDCloseInTheDistanceItem;
import com.firehostredux.fartsysadditions.item.AMDChipsOfNatureItem;
import com.firehostredux.fartsysadditions.item.AMDChipbloomItem;
import com.firehostredux.fartsysadditions.item.AMDChipSunItem;
import com.firehostredux.fartsysadditions.item.AMDChipOilJiggleTuneItem;
import com.firehostredux.fartsysadditions.item.AMDBurningBattlefieldItem;
import com.firehostredux.fartsysadditions.item.AMDBruteChiptuneItem;
import com.firehostredux.fartsysadditions.item.AMDBigBonedItem;
import com.firehostredux.fartsysadditions.item.AMDBetweenHeavenAndEarthItem;
import com.firehostredux.fartsysadditions.item.AMDBattleItem;
import com.firehostredux.fartsysadditions.item.AMDBattleAgainstATrueHeroItem;
import com.firehostredux.fartsysadditions.item.AMDBatCountryItem;
import com.firehostredux.fartsysadditions.item.AMDAthenaTheTirelessOneItem;
import com.firehostredux.fartsysadditions.item.AMDApexOfTheWorldItem;
import com.firehostredux.fartsysadditions.item.AMDAndLoveYouShallFindItem;
import com.firehostredux.fartsysadditions.item.AMDAndChipsYouShallFindItem;
import com.firehostredux.fartsysadditions.item.AMDALongFallItem;
import com.firehostredux.fartsysadditions.FartsysmagitechfantasyMod;

public class FartsysmagitechfantasyModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, FartsysmagitechfantasyMod.MODID);
	public static final RegistryObject<Item> DEBUG_ITEM = REGISTRY.register("debug_item", () -> new DebugItemItem());
	public static final RegistryObject<Item> SHART_ONE = REGISTRY.register("shart_one", () -> new ShartOneItem());
	public static final RegistryObject<Item> SHART_TEN = REGISTRY.register("shart_ten", () -> new ShartTenItem());
	public static final RegistryObject<Item> SHART_HUNDRED = REGISTRY.register("shart_hundred", () -> new ShartHundredItem());
	public static final RegistryObject<Item> SHART_THOUSAND = REGISTRY.register("shart_thousand", () -> new ShartThousandItem());
	public static final RegistryObject<Item> SHART_TEN_THOUSAND = REGISTRY.register("shart_ten_thousand", () -> new ShartTenThousandItem());
	public static final RegistryObject<Item> SHART_HUNDRED_THOUSAND = REGISTRY.register("shart_hundred_thousand", () -> new ShartHundredThousandItem());
	public static final RegistryObject<Item> SHART_MILLION = REGISTRY.register("shart_million", () -> new ShartMillionItem());
	public static final RegistryObject<Item> SHART_TEN_MILLION = REGISTRY.register("shart_ten_million", () -> new ShartTenMillionItem());
	public static final RegistryObject<Item> ROCK_SALT = block(FartsysmagitechfantasyModBlocks.ROCK_SALT);
	public static final RegistryObject<Item> SHART_SPECIAL = REGISTRY.register("shart_special", () -> new ShartSpecialItem());
	public static final RegistryObject<Item> BAG_O_ROCK_SALT = REGISTRY.register("bag_o_rock_salt", () -> new BagORockSaltItem());
	public static final RegistryObject<Item> PVC_DUST = REGISTRY.register("pvc_dust", () -> new PVCPlasticItem());
	public static final RegistryObject<Item> CRONUS = REGISTRY.register("cronus", () -> new CronusItem());
	public static final RegistryObject<Item> AMD_ATHENA_THE_TIRELESS_ONE = REGISTRY.register("amd_athena_the_tireless_one", () -> new AMDAthenaTheTirelessOneItem());
	public static final RegistryObject<Item> AMD_SCREAM = REGISTRY.register("amd_scream", () -> new AMDScreamItem());
	public static final RegistryObject<Item> AMD_TORN_FROM_THE_HEAVENS_ORCHESTRAL = REGISTRY.register("amd_torn_from_the_heavens_orchestral", () -> new AMDTornFromTheHeavensOrchestralItem());
	public static final RegistryObject<Item> AMD_FROM_THE_HEAVENS = REGISTRY.register("amd_from_the_heavens", () -> new AMDFromTheHeavensItem());
	public static final RegistryObject<Item> AMD_ESCAPE = REGISTRY.register("amd_escape", () -> new AMDEscapeItem());
	public static final RegistryObject<Item> AMD_CLOSE_IN_THE_DISTANCE = REGISTRY.register("amd_close_in_the_distance", () -> new AMDCloseInTheDistanceItem());
	public static final RegistryObject<Item> AMD_FOOTFALLS = REGISTRY.register("amd_footfalls", () -> new AMDFootfallsItem());
	public static final RegistryObject<Item> AMD_INSATIABLE = REGISTRY.register("amd_insatiable", () -> new AMDInsatiableItem());
	public static final RegistryObject<Item> AMD_TO_THE_EDGE = REGISTRY.register("amd_to_the_edge", () -> new AMDToTheEdgeItem());
	public static final RegistryObject<Item> AMD_AND_LOVE_YOU_SHALL_FIND = REGISTRY.register("amd_and_love_you_shall_find", () -> new AMDAndLoveYouShallFindItem());
	public static final RegistryObject<Item> AMD_LUNAR_WHALE = REGISTRY.register("amd_lunar_whale", () -> new AMDLunarWhaleItem());
	public static final RegistryObject<Item> AMD_SHADOWBRINGERS = REGISTRY.register("amd_shadowbringers", () -> new AMDShadowbringersItem());
	public static final RegistryObject<Item> AMD_METAL = REGISTRY.register("amd_metal", () -> new AMDMetalItem());
	public static final RegistryObject<Item> AMD_METAL_BRUTE_JUSTICE_MODE = REGISTRY.register("amd_metal_brute_justice_mode", () -> new AMDMetalBruteJusticeModeItem());
	public static final RegistryObject<Item> AMD_LOCUS = REGISTRY.register("amd_locus", () -> new AMDLocusItem());
	public static final RegistryObject<Item> AMD_PENITUS = REGISTRY.register("amd_penitus", () -> new AMDPenitusItem());
	public static final RegistryObject<Item> JR_ATHENA_THE_TIRELESS_ONE = REGISTRY.register("jr_athena_the_tireless_one", () -> new JRAthenaTheTirelessOneItem());
	public static final RegistryObject<Item> JR_SCREAM = REGISTRY.register("jr_scream", () -> new JRScreamItem());
	public static final RegistryObject<Item> JR_TORN_FROM_THE_HEAVENS_ORCHESTRAL = REGISTRY.register("jr_torn_from_the_heavens_orchestral", () -> new JRTornFromTheHeavensOrchestralItem());
	public static final RegistryObject<Item> JR_FROM_THE_HEAVENS = REGISTRY.register("jr_from_the_heavens", () -> new JRFromTheHeavensItem());
	public static final RegistryObject<Item> JR_ESCAPE = REGISTRY.register("jr_escape", () -> new JREscapeItem());
	public static final RegistryObject<Item> JR_CLOSE_IN_THE_DISTANCE = REGISTRY.register("jr_close_in_the_distance", () -> new JRCloseInTheDistanceItem());
	public static final RegistryObject<Item> JR_FOOTFALLS = REGISTRY.register("jr_footfalls", () -> new JRFootfallsItem());
	public static final RegistryObject<Item> JR_INSATIABLE = REGISTRY.register("jr_insatiable", () -> new JRInsatiableItem());
	public static final RegistryObject<Item> JR_TO_THE_EDGE = REGISTRY.register("jr_to_the_edge", () -> new JRToTheEdgeItem());
	public static final RegistryObject<Item> JR_AND_LOVE_YOU_SHALL_FIND = REGISTRY.register("jr_and_love_you_shall_find", () -> new JRAndLoveYouShallFindItem());
	public static final RegistryObject<Item> JR_LUNAR_WHALE = REGISTRY.register("jr_lunar_whale", () -> new JRLunarWhaleItem());
	public static final RegistryObject<Item> JR_SHADOWBRINGERS = REGISTRY.register("jr_shadowbringers", () -> new JRShadowbringersItem());
	public static final RegistryObject<Item> JR_METAL = REGISTRY.register("jr_metal", () -> new JRMetalItem());
	public static final RegistryObject<Item> JR_METAL_BRUTE_JUSTICE_MODE = REGISTRY.register("jr_metal_brute_justice_mode", () -> new JRMetalBruteJusticeModeItem());
	public static final RegistryObject<Item> JR_LOCUS = REGISTRY.register("jr_locus", () -> new JRLocusItem());
	public static final RegistryObject<Item> JR_PENITUS = REGISTRY.register("jr_penitus", () -> new JRPenitusItem());
	public static final RegistryObject<Item> FC_ATHENA_THE_TIRELESS_ONE = REGISTRY.register("fc_athena_the_tireless_one", () -> new FCAthenaTheTirelessOneItem());
	public static final RegistryObject<Item> FC_SCREAM = REGISTRY.register("fc_scream", () -> new FCScreamItem());
	public static final RegistryObject<Item> FC_TORN_FROM_THE_HEAVENS_ORCHESTRAL = REGISTRY.register("fc_torn_from_the_heavens_orchestral", () -> new FCTornFromTheHeavensOrchestralItem());
	public static final RegistryObject<Item> FC_FROM_THE_HEAVENS = REGISTRY.register("fc_from_the_heavens", () -> new FCFromTheHeavensItem());
	public static final RegistryObject<Item> FC_ESCAPE = REGISTRY.register("fc_escape", () -> new FCEscapeItem());
	public static final RegistryObject<Item> FC_CLOSE_IN_THE_DISTANCE = REGISTRY.register("fc_close_in_the_distance", () -> new FCCloseInTheDistanceItem());
	public static final RegistryObject<Item> FC_FOOTFALLS = REGISTRY.register("fc_footfalls", () -> new FCFootfallsItem());
	public static final RegistryObject<Item> FC_INSATIABLE = REGISTRY.register("fc_insatiable", () -> new FCInsatiableItem());
	public static final RegistryObject<Item> FC_TO_THE_EDGE = REGISTRY.register("fc_to_the_edge", () -> new FCToTheEdgeItem());
	public static final RegistryObject<Item> FC_AND_LOVE_YOU_SHALL_FIND = REGISTRY.register("fc_and_love_you_shall_find", () -> new FCAndLoveYouShallFindItem());
	public static final RegistryObject<Item> FC_LUNAR_WHALE = REGISTRY.register("fc_lunar_whale", () -> new FCLunarWhaleItem());
	public static final RegistryObject<Item> FC_METAL = REGISTRY.register("fc_metal", () -> new FCMetalItem());
	public static final RegistryObject<Item> FC_METAL_BRUTE_JUSTICE_MODE = REGISTRY.register("fc_metal_brute_justice_mode", () -> new FCMetalBruteJusticeModeItem());
	public static final RegistryObject<Item> FC_LOCUS = REGISTRY.register("fc_locus", () -> new FCLocusItem());
	public static final RegistryObject<Item> FC_PENITUS = REGISTRY.register("fc_penitus", () -> new FCPenitusItem());
	public static final RegistryObject<Item> SHARD_EARTH = REGISTRY.register("shard_earth", () -> new ShardEarthItem());
	public static final RegistryObject<Item> SHARD_FIRE = REGISTRY.register("shard_fire", () -> new ShardFireItem());
	public static final RegistryObject<Item> SHARD_ICE = REGISTRY.register("shard_ice", () -> new ShardIceItem());
	public static final RegistryObject<Item> SHARD_LIGHTNING = REGISTRY.register("shard_lightning", () -> new ShardLightningItem());
	public static final RegistryObject<Item> SHARD_UNASPECTED = REGISTRY.register("shard_unaspected", () -> new ShardUnaspectedItem());
	public static final RegistryObject<Item> SHARD_WATER = REGISTRY.register("shard_water", () -> new ShardWaterItem());
	public static final RegistryObject<Item> SHARD_WIND = REGISTRY.register("shard_wind", () -> new ShardWindItem());
	public static final RegistryObject<Item> CRYSTAL_EARTH = REGISTRY.register("crystal_earth", () -> new CrystalEarthItem());
	public static final RegistryObject<Item> CRYSTAL_FIRE = REGISTRY.register("crystal_fire", () -> new CrystalFireItem());
	public static final RegistryObject<Item> CRYSTAL_ICE = REGISTRY.register("crystal_ice", () -> new CrystalIceItem());
	public static final RegistryObject<Item> CRYSTAL_LIGHTNING = REGISTRY.register("crystal_lightning", () -> new CrystalLightningItem());
	public static final RegistryObject<Item> CRYSTAL_UNASPECTED = REGISTRY.register("crystal_unaspected", () -> new CrystalUnaspectedItem());
	public static final RegistryObject<Item> CRYSTAL_WATER = REGISTRY.register("crystal_water", () -> new CrystalWaterItem());
	public static final RegistryObject<Item> CRYSTAL_WIND = REGISTRY.register("crystal_wind", () -> new CrystalWindItem());
	public static final RegistryObject<Item> CLUSTER_EARTH = REGISTRY.register("cluster_earth", () -> new ClusterEarthItem());
	public static final RegistryObject<Item> CLUSTER_FIRE = REGISTRY.register("cluster_fire", () -> new ClusterFireItem());
	public static final RegistryObject<Item> CLUSTER_ICE = REGISTRY.register("cluster_ice", () -> new ClusterIceItem());
	public static final RegistryObject<Item> CLUSTER_LIGHTNING = REGISTRY.register("cluster_lightning", () -> new ClusterLightningItem());
	public static final RegistryObject<Item> CLUSTER_UNASPECTED = REGISTRY.register("cluster_unaspected", () -> new ClusterUnaspectedItem());
	public static final RegistryObject<Item> CLUSTER_WATER = REGISTRY.register("cluster_water", () -> new ClusterWaterItem());
	public static final RegistryObject<Item> CLUSTER_WIND = REGISTRY.register("cluster_wind", () -> new ClusterWindItem());
	public static final RegistryObject<Item> BLANK_G_1_JR = REGISTRY.register("blank_g_1_jr", () -> new BlankG1JRItem());
	public static final RegistryObject<Item> BLANK_G_2_JR = REGISTRY.register("blank_g_2_jr", () -> new BlankG2JRItem());
	public static final RegistryObject<Item> BLANK_G_3_JR = REGISTRY.register("blank_g_3_jr", () -> new BlankG3JRItem());
	public static final RegistryObject<Item> ORE_UNASPECTED = block(FartsysmagitechfantasyModBlocks.ORE_UNASPECTED);
	public static final RegistryObject<Item> AMD_BIG_BONED = REGISTRY.register("amd_big_boned", () -> new AMDBigBonedItem());
	public static final RegistryObject<Item> AMD_IMAGINATION = REGISTRY.register("amd_imagination", () -> new AMDImaginationItem());
	public static final RegistryObject<Item> AMD_LUNACY = REGISTRY.register("amd_lunacy", () -> new AMDLunacyItem());
	public static final RegistryObject<Item> AMD_NIGHTBLOOM = REGISTRY.register("amd_nightbloom", () -> new AMDNightbloomItem());
	public static final RegistryObject<Item> AMD_PA_PAYA = REGISTRY.register("amd_pa_paya", () -> new AMDPaPayaItem());
	public static final RegistryObject<Item> AMD_STEEL_REASON = REGISTRY.register("amd_steel_reason", () -> new AMDSteelReasonItem());
	public static final RegistryObject<Item> AMD_THE_EWER_BRIMMETH = REGISTRY.register("amd_the_ewer_brimmeth", () -> new AMDTheEwerBrimmethItem());
	public static final RegistryObject<Item> AMD_WAYWARD_DAUGHTER = REGISTRY.register("amd_wayward_daughter", () -> new AMDWaywardDaughterItem());
	public static final RegistryObject<Item> JR_BIG_BONED = REGISTRY.register("jr_big_boned", () -> new JRBigBonedItem());
	public static final RegistryObject<Item> JR_IMAGINATION = REGISTRY.register("jr_imagination", () -> new JRImaginationItem());
	public static final RegistryObject<Item> JR_LUNACY = REGISTRY.register("jr_lunacy", () -> new JRLunacyItem());
	public static final RegistryObject<Item> JR_NIGHTBLOOM = REGISTRY.register("jr_nightbloom", () -> new JRNightbloomItem());
	public static final RegistryObject<Item> JR_PA_PAYA = REGISTRY.register("jr_pa_paya", () -> new JRPaPayaItem());
	public static final RegistryObject<Item> JR_STEEL_REASON = REGISTRY.register("jr_steel_reason", () -> new JRSteelReasonItem());
	public static final RegistryObject<Item> JR_THE_EWER_BRIMMETH = REGISTRY.register("jr_the_ewer_brimmeth", () -> new JRTheEwerBrimmethItem());
	public static final RegistryObject<Item> JR_WAYWARD_DAUGHTER = REGISTRY.register("jr_wayward_daughter", () -> new JRWaywardDaughterItem());
	public static final RegistryObject<Item> FC_BIG_BONED = REGISTRY.register("fc_big_boned", () -> new FCBigBonedItem());
	public static final RegistryObject<Item> FC_IMAGINATION = REGISTRY.register("fc_imagination", () -> new FCImaginationItem());
	public static final RegistryObject<Item> FC_LUNACY = REGISTRY.register("fc_lunacy", () -> new FCLunacyItem());
	public static final RegistryObject<Item> FC_NIGHTBLOOM = REGISTRY.register("fc_nightbloom", () -> new FCNightbloomItem());
	public static final RegistryObject<Item> FC_STEEL_REASON = REGISTRY.register("fc_steel_reason", () -> new FCSteelReasonItem());
	public static final RegistryObject<Item> FC_THE_EWER_BRIMMETH = REGISTRY.register("fc_the_ewer_brimmeth", () -> new FCTheEwerBrimmethItem());
	public static final RegistryObject<Item> FC_WAYWARD_DAUGHTER = REGISTRY.register("fc_wayward_daughter", () -> new FCWaywardDaughterItem());
	public static final RegistryObject<Item> FC_SHADOWBRINGERS = REGISTRY.register("fc_shadowbringers", () -> new FCShadowbringersItem());
	public static final RegistryObject<Item> ORE_EARTH = block(FartsysmagitechfantasyModBlocks.ORE_EARTH);
	public static final RegistryObject<Item> ORE_FIRE = block(FartsysmagitechfantasyModBlocks.ORE_FIRE);
	public static final RegistryObject<Item> ORE_FIRE_OVERWORLD = block(FartsysmagitechfantasyModBlocks.ORE_FIRE_OVERWORLD);
	public static final RegistryObject<Item> ORE_ICE = block(FartsysmagitechfantasyModBlocks.ORE_ICE);
	public static final RegistryObject<Item> ORE_LIGHTNING = block(FartsysmagitechfantasyModBlocks.ORE_LIGHTNING);
	public static final RegistryObject<Item> ORE_LIGHTNING_OVERWORLD = block(FartsysmagitechfantasyModBlocks.ORE_LIGHTNING_OVERWORLD);
	public static final RegistryObject<Item> ORE_WATER = block(FartsysmagitechfantasyModBlocks.ORE_WATER);
	public static final RegistryObject<Item> ORE_WIND = block(FartsysmagitechfantasyModBlocks.ORE_WIND);
	public static final RegistryObject<Item> ENCHANTED_IRON_INK = REGISTRY.register("enchanted_iron_ink", () -> new EnchantedIronInkItem());
	public static final RegistryObject<Item> ENCHANTED_GOLD_INK = REGISTRY.register("enchanted_gold_ink", () -> new EnchantedGoldInkItem());
	public static final RegistryObject<Item> ENCHANTED_DIAMOND_INK = REGISTRY.register("enchanted_diamond_ink", () -> new EnchantedDiamondInkItem());
	public static final RegistryObject<Item> ENCHANTED_LAPIS_INK = REGISTRY.register("enchanted_lapis_ink", () -> new EnchantedLapisInkItem());
	public static final RegistryObject<Item> ENCHANTED_REDSTONE_INK = REGISTRY.register("enchanted_redstone_ink", () -> new EnchantedRedstoneInkItem());
	public static final RegistryObject<Item> ENCHANTED_GLOWSTONE_INK = REGISTRY.register("enchanted_glowstone_ink", () -> new EnchantedGlowstoneInkItem());
	public static final RegistryObject<Item> ENCHANTED_EMERALD_INK = REGISTRY.register("enchanted_emerald_ink", () -> new EnchantedEmeraldInkItem());
	public static final RegistryObject<Item> ENCHANTED_QUARTZ_INK = REGISTRY.register("enchanted_quartz_ink", () -> new EnchantedQuartzInkItem());
	public static final RegistryObject<Item> ENCHANTED_NETHER_BRICK_INK = REGISTRY.register("enchanted_nether_brick_ink", () -> new EnchantedNetherBrickInkItem());
	public static final RegistryObject<Item> ENCHANTED_ENDER_PEARL_INK = REGISTRY.register("enchanted_ender_pearl_ink", () -> new EnchantedEnderPearlInkItem());
	public static final RegistryObject<Item> LA_CUCURACHA = REGISTRY.register("la_cucuracha", () -> new LaCucurachaItem());
	public static final RegistryObject<Item> AMD_EXPONENTIAL_ENTROPY_PRIMALS = REGISTRY.register("amd_exponential_entropy_primals", () -> new AMDExponentialEntropyPrimalsItem());
	public static final RegistryObject<Item> JR_EXPONENTIAL_ENTROPY_PRIMALS = REGISTRY.register("jr_exponential_entropy_primals", () -> new JRExponentialEntropyPrimalsItem());
	public static final RegistryObject<Item> FC_EXPONENTIAL_ENTROPY_PRIMALS = REGISTRY.register("fc_exponential_entropy_primals", () -> new FCExponentialEntropyPrimalsItem());
	public static final RegistryObject<Item> SHART_TWO = REGISTRY.register("shart_two", () -> new ShartTwoItem());
	public static final RegistryObject<Item> SHART_TWENTY = REGISTRY.register("shart_twenty", () -> new ShartTwentyItem());
	public static final RegistryObject<Item> SHART_TWO_HUNDRED = REGISTRY.register("shart_two_hundred", () -> new ShartTwoHundredItem());
	public static final RegistryObject<Item> SHART_TWO_THOUSAND = REGISTRY.register("shart_two_thousand", () -> new ShartTwoThousandItem());
	public static final RegistryObject<Item> SHART_TWENTY_THOUSAND = REGISTRY.register("shart_twenty_thousand", () -> new ShartTwentyThousandItem());
	public static final RegistryObject<Item> SHART_TWO_HUNDRED_THOUSAND = REGISTRY.register("shart_two_hundred_thousand", () -> new ShartTwoHundredThousandItem());
	public static final RegistryObject<Item> SHART_TWO_MILLION = REGISTRY.register("shart_two_million", () -> new ShartTwoMillionItem());
	public static final RegistryObject<Item> SHART_TWENTY_MILLION = REGISTRY.register("shart_twenty_million", () -> new ShartTwentyMillionItem());
	public static final RegistryObject<Item> AMD_BATTLE_AGAINST_A_TRUE_HERO = REGISTRY.register("amd_battle_against_a_true_hero", () -> new AMDBattleAgainstATrueHeroItem());
	public static final RegistryObject<Item> AMD_BETWEEN_HEAVEN_AND_EARTH = REGISTRY.register("amd_between_heaven_and_earth", () -> new AMDBetweenHeavenAndEarthItem());
	public static final RegistryObject<Item> AMD_BAT_COUNTRY = REGISTRY.register("amd_bat_country", () -> new AMDBatCountryItem());
	public static final RegistryObject<Item> AMD_CHIP_OIL_JIGGLE_TUNE = REGISTRY.register("amd_chip_oil_jiggle_tune", () -> new AMDChipOilJiggleTuneItem());
	public static final RegistryObject<Item> AMD_APEX_OF_THE_WORLD = REGISTRY.register("amd_apex_of_the_world", () -> new AMDApexOfTheWorldItem());
	public static final RegistryObject<Item> AMD_CHIP_SUN = REGISTRY.register("amd_chip_sun", () -> new AMDChipSunItem());
	public static final RegistryObject<Item> AMD_CHIPS_OF_NATURE = REGISTRY.register("amd_chips_of_nature", () -> new AMDChipsOfNatureItem());
	public static final RegistryObject<Item> AMD_DEVIL_TRIGGER = REGISTRY.register("amd_devil_trigger", () -> new AMDDevilTriggerItem());
	public static final RegistryObject<Item> AMD_DRIFTVEIL_CITY = REGISTRY.register("amd_driftveil_city", () -> new AMDDriftveilCityItem());
	public static final RegistryObject<Item> AMD_DYNAMITE = REGISTRY.register("amd_dynamite", () -> new AMDDynamiteItem());
	public static final RegistryObject<Item> AMD_EXPONENTIAL_CHIPTUNE = REGISTRY.register("amd_exponential_chiptune", () -> new AMDExponentialChiptuneItem());
	public static final RegistryObject<Item> AMD_NEVER_GONNA_GIVE_YOU_UP = REGISTRY.register("amd_never_gonna_give_you_up", () -> new AMDNeverGonnaGiveYouUpItem());
	public static final RegistryObject<Item> AMD_MOTOR_OIL_JIGGLE_JUNGLE = REGISTRY.register("amd_motor_oil_jiggle_jungle", () -> new AMDMotorOilJiggleJungleItem());
	public static final RegistryObject<Item> AMD_SWEATY_SOCKS = REGISTRY.register("amd_sweaty_socks", () -> new AMDSweatySocksItem());
	public static final RegistryObject<Item> AMD_SWEATY_CHIPS = REGISTRY.register("amd_sweaty_chips", () -> new AMDSweatyChipsItem());
	public static final RegistryObject<Item> AMD_LANDSLIDE = REGISTRY.register("amd_landslide", () -> new AMDLandslideItem());
	public static final RegistryObject<Item> JR_LANDSLIDE = REGISTRY.register("jr_landslide", () -> new JRLandslideItem());
	public static final RegistryObject<Item> AMD_BRUTE_CHIPTUNE = REGISTRY.register("amd_brute_chiptune", () -> new AMDBruteChiptuneItem());
	public static final RegistryObject<Item> AMD_MELANCHIPTUNE = REGISTRY.register("amd_melanchiptune", () -> new AMDMelanchiptuneItem());
	public static final RegistryObject<Item> AMD_TWICE_STRICKEN_INSTRUMENTAL = REGISTRY.register("amd_twice_stricken_instrumental", () -> new AMDTwiceStrickenInstrumentalItem());
	public static final RegistryObject<Item> AMD_TWICE_STRICKEN = REGISTRY.register("amd_twice_stricken", () -> new AMDTwiceStrickenItem());
	public static final RegistryObject<Item> JR_TWICE_STRICKEN = REGISTRY.register("jr_twice_stricken", () -> new JRTwiceStrickenItem());
	public static final RegistryObject<Item> AMD_INTERPHOS_P_1 = REGISTRY.register("amd_interphos_p_1", () -> new AMDInterphosP1Item());
	public static final RegistryObject<Item> JR_INTERPHOS_P_1 = REGISTRY.register("jr_interphos_p_1", () -> new JRInterphosP1Item());
	public static final RegistryObject<Item> AMDA_LONG_FALL = REGISTRY.register("amda_long_fall", () -> new AMDALongFallItem());
	public static final RegistryObject<Item> JRA_LONG_FALL = REGISTRY.register("jra_long_fall", () -> new JRALongFallItem());
	public static final RegistryObject<Item> AMD_TRIUMPH_DISSIDIA_NT = REGISTRY.register("amd_triumph_dissidia_nt", () -> new AMDTriumphDissidiaNTItem());
	public static final RegistryObject<Item> JR_TRIUMPH_DISSIDIA_NT = REGISTRY.register("jr_triumph_dissidia_nt", () -> new JRTriumphDissidiaNTItem());
	public static final RegistryObject<Item> AMD_PAPAYA_DEMASTERED = REGISTRY.register("amd_papaya_demastered", () -> new AMDPapayaDemasteredItem());
	public static final RegistryObject<Item> JR_PAPAYA_DEMASTERED = REGISTRY.register("jr_papaya_demastered", () -> new JRPapayaDemasteredItem());
	public static final RegistryObject<Item> AMD_WHO_BRINGS_SHADOW = REGISTRY.register("amd_who_brings_shadow", () -> new AMDWhoBringsShadowItem());
	public static final RegistryObject<Item> JR_WHO_BRINGS_SHADOW = REGISTRY.register("jr_who_brings_shadow", () -> new JRWhoBringsShadowItem());
	public static final RegistryObject<Item> AMD_TOMORROW_AND_TOMORROW = REGISTRY.register("amd_tomorrow_and_tomorrow", () -> new AMDTomorrowAndTomorrowItem());
	public static final RegistryObject<Item> JR_TOMORROW_AND_TOMORROW = REGISTRY.register("jr_tomorrow_and_tomorrow", () -> new JRTomorrowAndTomorrowItem());
	public static final RegistryObject<Item> AMD_BATTLE = REGISTRY.register("amd_battle", () -> new AMDBattleItem());
	public static final RegistryObject<Item> AMD_YOU_WILL_KNOW_OUR_NAMES_REMASTERED = REGISTRY.register("amd_you_will_know_our_names_remastered", () -> new AMDYouWillKnowOurNamesRemasteredItem());
	public static final RegistryObject<Item> AMD_BURNING_BATTLEFIELD = REGISTRY.register("amd_burning_battlefield", () -> new AMDBurningBattlefieldItem());
	public static final RegistryObject<Item> AMD_SANDS_OF_AMBER = REGISTRY.register("amd_sands_of_amber", () -> new AMDSandsOfAmberItem());
	public static final RegistryObject<Item> JR_SANDS_OF_AMBER = REGISTRY.register("jr_sands_of_amber", () -> new JRSandsOfAmberItem());
	public static final RegistryObject<Item> AMD_FIEND = REGISTRY.register("amd_fiend", () -> new AMDFiendItem());
	public static final RegistryObject<Item> JR_FIEND = REGISTRY.register("jr_fiend", () -> new JRFiendItem());
	public static final RegistryObject<Item> AMD_NEATH_DARK_WATERS = REGISTRY.register("amd_neath_dark_waters", () -> new AMDNeathDarkWatersItem());
	public static final RegistryObject<Item> JR_NEATH_DARK_WATERS = REGISTRY.register("jr_neath_dark_waters", () -> new JRNeathDarkWatersItem());
	public static final RegistryObject<Item> AMD_AND_CHIPS_YOU_SHALL_FIND = REGISTRY.register("amd_and_chips_you_shall_find", () -> new AMDAndChipsYouShallFindItem());
	public static final RegistryObject<Item> AMD_INSATIABLE_CHIPS = REGISTRY.register("amd_insatiable_chips", () -> new AMDInsatiableChipsItem());
	public static final RegistryObject<Item> AMD_HIC_SVNT_LEONES = REGISTRY.register("amd_hic_svnt_leones", () -> new AMDHicSvntLeonesItem());
	public static final RegistryObject<Item> JR_HIC_SVNT_LEONES = REGISTRY.register("jr_hic_svnt_leones", () -> new JRHicSvntLeonesItem());
	public static final RegistryObject<Item> AMD_ONE_AMONGST_THE_WEARY = REGISTRY.register("amd_one_amongst_the_weary", () -> new AMDOneAmongstTheWearyItem());
	public static final RegistryObject<Item> JR_ONE_AMONGST_THE_WEARY = REGISTRY.register("jr_one_amongst_the_weary", () -> new JROneAmongstTheWearyItem());
	public static final RegistryObject<Item> WAFFLE_OF_ASS_DESTRUCTION = REGISTRY.register("waffle_of_ass_destruction", () -> new WaffleOfAssDestructionItem());
	public static final RegistryObject<Item> AMD_CHIPBLOOM = REGISTRY.register("amd_chipbloom", () -> new AMDChipbloomItem());
	public static final RegistryObject<Item> AMD_GIVE_IT_ALL = REGISTRY.register("amd_give_it_all", () -> new AMDGiveItAllItem());
	public static final RegistryObject<Item> JR_GIVE_IT_ALL = REGISTRY.register("jr_give_it_all", () -> new JRGiveItAllItem());
	public static final RegistryObject<Item> FC_FIEND = REGISTRY.register("fc_fiend", () -> new FCFiendItem());
	public static final RegistryObject<Item> TESTENT_SPAWN_EGG = REGISTRY.register("testent_spawn_egg", () -> new ForgeSpawnEggItem(FartsysmagitechfantasyModEntities.TESTENT, -1, -26113, new Item.Properties()));

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
