/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package com.firehostredux.fartsysadditions;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class FartsysAdditionsModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();

	public FartsysAdditionsModElements() {
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.penitus"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.penitus")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.battleonthebigbridge"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.battleonthebigbridge")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.primals.brutejusticemode"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.primals.brutejusticemode")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.exponentialentropy"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.exponentialentropy")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.brutejusticemode"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.brutejusticemode")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.primals.exponentialentropy"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.primals.exponentialentropy")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.infinity"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.infinity")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.locus"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.locus")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.primals.locus"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.primals.locus")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.metal"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.metal")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.outoftime"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.outoftime")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.silentregardofstars"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.silentregardofstars")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.knowledgeneversleeps"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.knowledgeneversleeps")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.alandlongdead"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.alandlongdead")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.agentofinquiry"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.agentofinquiry")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.lunarwhale"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.lunarwhale")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.closeinthedistance"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.closeinthedistance")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.footfalls"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.footfalls")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.undertheweight"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.undertheweight")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.landslide"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.landslide")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.woethatismadness"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.woethatismadness")));
		sounds.put(new ResourceLocation("fartsys_additions", "touhou.badapple"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "touhou.badapple")));
		sounds.put(new ResourceLocation("fartsys_additions", "touhou.necrofantasia"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "touhou.necrofantasia")));
		sounds.put(new ResourceLocation("fartsys_additions", "touhou.cosmicmind"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "touhou.cosmicmind")));
		sounds.put(new ResourceLocation("fartsys_additions", "touhou.nuclearfusion"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "touhou.nuclearfusion")));
		sounds.put(new ResourceLocation("fartsys_additions", "touhou.unowenwasher"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "touhou.unowenwasher")));
		sounds.put(new ResourceLocation("fartsys_additions", "demetori.orientaldarkflight"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "demetori.orientaldarkflight")));
		sounds.put(new ResourceLocation("fartsys_additions", "demetori.necrofantasia"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "demetori.necrofantasia")));
		sounds.put(new ResourceLocation("fartsys_additions", "demetori.worldsend"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "demetori.worldsend")));
		sounds.put(new ResourceLocation("fartsys_additions", "dmc5.deviltrigger"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "dmc5.deviltrigger")));
		sounds.put(new ResourceLocation("fartsys_additions", "dmc5.burythelightmission20"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "dmc5.burythelightmission20")));
		sounds.put(new ResourceLocation("fartsys_additions", "dmc5.silverbullet"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "dmc5.silverbullet")));
		sounds.put(new ResourceLocation("fartsys_additions", "nge.cruelangelsthesis"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "nge.cruelangelsthesis")));
		sounds.put(new ResourceLocation("fartsys_additions", "slipknot.psychosocial"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "slipknot.psychosocial")));
		sounds.put(new ResourceLocation("fartsys_additions", "xc.youwillknowournames"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "xc.youwillknowournames")));
		sounds.put(new ResourceLocation("fartsys_additions", "xc2.battle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "xc2.battle")));
		sounds.put(new ResourceLocation("fartsys_additions", "ffxiv.shadowbringers"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "ffxiv.shadowbringers")));
		sounds.put(new ResourceLocation("fartsys_additions", "kbr.dededestroyerz"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "kbr.dededestroyerz")));
		sounds.put(new ResourceLocation("fartsys_additions", "smash.pixelsofglory"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "smash.pixelsofglory")));
		sounds.put(new ResourceLocation("fartsys_additions", "emone"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "emone")));
		sounds.put(new ResourceLocation("fartsys_additions", "woad"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fartsys_additions", "woad")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("fartsys_additions").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == FartsysAdditionsModElements.ModElement.class)
						elements.add((FartsysAdditionsModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(FartsysAdditionsModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	private int messageID = 0;

	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		FartsysAdditionsMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}

		protected final FartsysAdditionsModElements elements;
		protected final int sortid;

		public ModElement(FartsysAdditionsModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
